### ISSUE TITLE
Automate build process

### ISSUE THREAD

**Issue by piranna** [Coretool/noGUI#1]
Add a script that do automaticaly all the tasks described in the readme, so just by executing that script will download and build all the source code and dependencies. This would make it easier to use and to publish later the project as a npm package :-)

**Comment by Coretool** [comment]
Scheduled for tomorrow =)

**Comment by piranna** [comment]
Perfect :-) What build tools and libraries are need to have installed?
Maybe we would need to include a list of them or add an installDependencies
script...
El 7/2/2016 19:18, "John Green" notifications@github.com escribió:

Scheduled for tomorrow =)

**Comment by Coretool** [comment]
Hm... I have to check that... I know that it is different form distro to distro (e.g. arch linux doesn't need any additional packages while ubuntu needs a ton of them)

**Comment by piranna** [comment]
Don't worry, I can be able to check it on Ubuntu myself :-) I'll try to do
it tomorrow.

**Comment by Coretool** [comment]
I'll probably create multiple scripts -> one to fetch the dependencies and one to do build (this will be the same on all distros)

**Comment by piranna** [comment]
> I'll probably create multiple scripts -> one to fetch the dependencies
> and one to do build (this will be the same on all distros)

Great :-) Do first the build one since you have allready the instructions
on the readme so I can check it on my machine ;-)

**Comment by Coretool** [comment]
The script seems to be working ... However... I won't be able to push it before tomorrow :/

**Comment by piranna** [comment]
Lol! I was just checking if there was any update on the project :-P Ok,
tame your time :-)

OffTopic: why do you have two users? :-/

**Comment by piranna** [comment]
Hi @Coretool, have you been able to get some progress with the build scripts? I'm freaking busy lately with my work, but wanted to give them a try... :-)

**Comment by Coretool** [comment]
Yeah ^^ they are on my desktop right now. The only thing I have to do is upload them ^^

**Comment by piranna** [comment]
Lol :-P Ok, keep me informed :-) What system are you using for development?

**Comment by Coretool** [comment]
I use Arch Linux most of the time, since it allows me to costumize it 'to the limit'. However, Ubuntu (Mate) is also one of my installed OSs :)

**Comment by piranna** [comment]
> However, Ubuntu (Mate) is also one of my installed OSs :)

Ey, me too! :D Ubuntu Unity sucks... :-P

**Comment by Coretool** [comment]
@piranna : Pushed it... hope it works =)

**Comment by piranna** [comment]
Well... I get a linker error :-(

```
make[3]: Entering directory '/home/piranna/Proyectos/noGUI/build/qtdeclarative/tools/qml'
moc /home/piranna/Proyectos/noGUI/deps/qt5/qtdeclarative/tools/qml/main.cpp
compiling qml_plugin_import.cpp
compiling qml_qml_plugin_import.cpp
rcc /home/piranna/Proyectos/noGUI/deps/qt5/qtdeclarative/tools/qml/qml.qrc
moc /home/piranna/Proyectos/noGUI/deps/qt5/qtdeclarative/tools/qml/conf.h
compiling /home/piranna/Proyectos/noGUI/deps/qt5/qtdeclarative/tools/qml/main.cpp
compiling .rcc/qrc_qml.cpp
compiling .moc/moc_conf.cpp
linking ../../bin/qml
/home/piranna/Proyectos/noGUI/build/qtdeclarative/lib/libQt5Qml.a(qqmldebugconnector.o):qqmldebugconnector.cpp:function _GLOBAL__sub_I_qqmldebugconnector.cpp: error: referencia a 'qt_static_plugin_QQmlInspectorServiceFactory()' sin definir
collect2: error: ld returned 1 exit status
Makefile:73: recipe for target '../../bin/qml' failed
make[3]: *** [../../bin/qml] Error 1
make[3]: Leaving directory '/home/piranna/Proyectos/noGUI/build/qtdeclarative/tools/qml'
Makefile:96: recipe for target 'sub-qml-make_first' failed
make[2]: *** [sub-qml-make_first] Error 2
make[2]: Leaving directory '/home/piranna/Proyectos/noGUI/build/qtdeclarative/tools'
Makefile:70: recipe for target 'sub-tools-make_first' failed
make[1]: *** [sub-tools-make_first] Error 2
make[1]: Leaving directory '/home/piranna/Proyectos/noGUI/build/qtdeclarative'
Makefile:299: recipe for target 'module-qtdeclarative-make_first' failed
make: *** [module-qtdeclarative-make_first] Error 2
```

The problematic entry is

```
/home/piranna/Proyectos/noGUI/build/qtdeclarative/lib/libQt5Qml.a(qqmldebugconnector.o):qqmldebugconnector.cpp:function _GLOBAL__sub_I_qqmldebugconnector.cpp: error: referencia a 'qt_static_plugin_QQmlInspectorServiceFactory()' sin definir
```

Seems `qt_static_plugin_QQmlInspectorServiceFactory` is not defined. I have disabled the build of the tools, but they are still being build don't know why. :-( Could you be able to check out my [fork](https://github.com/piranna/noGUI) and tell if it works for you? I've done some clean-ups and optimizations on the build to don't use system libraries. Also, I'm worried about this warning:

```
WARNING: Using static linking will disable the WebKit module.
```

Could you be able to send me an output of your `ldd` output?

**Comment by Coretool** [comment]
HM... The build seems to run eine for me, don't know why ... I will look at this later today... Would you like to push your script to noGui ;) I like that !!

**Comment by Coretool** [comment]
And... Why am I able to use a static WebKit and you aren't... So many strange things

**Comment by Coretool** [comment]
Hm ^^ now I know why... I wasn't using the newst version... IT ISN'T POSSIBLE (anymore)...

**Comment by Coretool** [comment]
Would it be OK to just bundle a minimal QT version and don't build (everything/) it statically (?) until I found an alternative...

**Comment by piranna** [comment]
> Would you like to push your script to noGui ;) I like that !!

[Done](https://github.com/Coretool/noGUI/pull/5) ;-)

> Hm ^^ now I know why... I wasn't using the newst version... IT ISN'T POSSIBLE (anymore)...

What version was you using? Maybe we can use that... or maybe the problem is your we using your system ones... :-/

> Would it be OK to just bundle a minimal QT version and don't build (everything/) it statically (?) until I found an alternative...

Yeah, ideally we should do that, Qt is really huge and we don't need everything...

**Comment by Coretool** [comment]
Hm... it was QT4.7 or something like that... I created a new branch (non-static) to which I will push a non static version  with the needed libs included

**Comment by piranna** [comment]
:+1:

**Comment by piranna** [comment]
https://github.com/ariya/phantomjs/blob/master/build.py

This is GOLD! :-D There's a lot of flags like `-no-qml-debug` that we could use! :-D

**Comment by Coretool** [comment]
Giant ./configure parameter list incoming ^^

**Comment by piranna** [comment]
That's not necesarily bad... :-) Also take in account that a lot of them are due to disable graphics support, so we would not set them... ;-)

P.D.: it's cool to have a similar timezone :-D

**Comment by Coretool** [comment]
Yeah ! It's a huge plus to share the timezone =)

**Comment by piranna** [comment]
> Yeah ! It's a huge plus to share the timezone =)

^^

Ok, so are you going to test with the no-static branch? I could give a try to some of this flags while you are doing that...

**Comment by Coretool** [comment]
Yeah, that's a good idea...

**Comment by piranna** [comment]
Ok, I'll put the machine to work ;-)

**Comment by Coretool** [comment]
:+1:

**Comment by piranna** [comment]
Seems PhantomJS [is using only qtbase](https://github.com/ariya/phantomjs/tree/master/src/qt) instead of full Qt, maybe we should do the same... In fact, I think we should use them as reference the same way I did with CLFS-Embebed to create the NodeOS cross-compiler, what do you think? :-)

**Comment by Coretool** [comment]
Good idea ->  qtbase + webkitwidgets ?

**Comment by piranna** [comment]
Seems webkitwidgets is a different thing.

**Comment by Coretool** [comment]
Yeah...  That's the problem :/

**Comment by piranna** [comment]
Why do you think so? I think the PhantomJS script is really clear about the steps to follow...

**Comment by Coretool** [comment]
> QTWebkit : Classes for a WebKit2 based implementation and a QML API. Deprecated in favor of Qt WebEngine. (QT WIKI)

Looks like we are searching Qt WebEngine ?

**Comment by Coretool** [comment]
Take a look at the wiki posts [here](https://wiki.qt.io/QtWebEngine) ...

**Comment by piranna** [comment]
QtWebkit are the (old) bindings for Webkit, that's nothing bad about them, but it's only a web renderer and has been deprecated. QtWebEngine are the (new) bindings over Chrome, that's a full-fledged browser. I was surprised PhantomJS repo is using QtWebkit, but it's ok for me.

**Comment by Coretool** [comment]
Hm... I'm trying to find out if I can compile QtWebEngine statically

**Comment by Coretool** [comment]
`./configure  -no-phonon -no-phonon-backend -no-script -no-scripttools -no-multimedia -no-qt3support -fast -no-script -no-scripttools -no-qt3support -nomake demos -nomake tools -nomake examples` ?

**Comment by Coretool** [comment]
`./configure -opensource -confirm-license  -fast -no-sql-sqlite -no-qt3support -no-xmlpatterns -no-multimedia -no-audio-backend -no-phonon -no-phonon-backend -svg -webkit -no-javascript-jit -no-script -no-scripttools -no-declarative  -qt-zlib -qt-gif -qt-libtiff -qt-libmng -qt-libjpeg -openssl -nomake demos -nomake examples -no-nis -no-cups -no-iconv -no-dbus - -linuxfb -no-armfpa  -qt-freetype -qconfig tess -opengl -no-gfx-multiscreen`

**Comment by Coretool** [comment]
Well then, let's use the phantom.js script

**Comment by Coretool** [comment]
(I'll move this to a new Issue since it's slightly off topic ^^)
