### ISSUE TITLE
noGUI on mac

### ISSUE THREAD

**Issue by jaumard** [Coretool/noGUI#11]
I'm trying to run `./build.sh` on mac and I have this error : 

```
...
Creating qmake...
Done.
Running configuration tests (phase 2)...
The test for linking against libxcb failed!
 Use of pkg-config is not enabled, maybe you want to pass -pkg-config?
 You might need to install dependency packages for libxcb.
 See src/plugins/platforms/xcb/README.
rmdir: illegal option -- -
usage: rmdir [-p] directory ...
```

Any idea of on fix this ?

**Comment by piranna** [comment]
NodeOS needs to be build on a Linux system, reference is Ubuntu. I tried to port the build process to Mac but there was no luck :-( Maybe noGUI could be ported, but you'll need to do it yourself. If you manage to do so, pull-requests are welcome :-)

**Comment by jaumard** [comment]
Thanks @piranna ! I will try to successfully build it on Ubuntu first ^^ I never work on such project before, I don't know if I able to help here. I will take a look :) but for know it's look like magic (or dark force lol)

**Comment by jaumard** [comment]
@piranna same error on ubuntu :/ I try `apt-get install xcb` but it's not fixing the error... Any idea ?

**Comment by Coretool** [comment]
@jaumard Isn't the package called libxcb ? See https://wiki.qt.io/Building_Qt_5_from_Git for more information :) 

Don't forget to run the `install-dependencies.sh` script !

**Comment by piranna** [comment]
Use my fork, I have it fixed.

**Comment by Coretool** [comment]
@piranna What did you change ?

**Comment by jaumard** [comment]
I try but `Unable to locate package libxcb` and libxcb1 already installed.  I will try your fork @piranna and let you know

**Comment by jaumard** [comment]
@piranna same on your fork... maybe something is missing on my system but I can't figure what it is :/

**Comment by jaumard** [comment]
I use a fresh ubuntu VM to build this and most `dev` packages are not installed. After installing some missing packages :

> Required packages:
> libxcb1 libxcb1-dev libx11-xcb1 libx11-xcb-dev libxcb-keysyms1 libxcb-keysyms1-dev libxcb-image0 libxcb-image0-dev libxcb-shm0 libxcb-shm0-dev libxcb-icccm1 libxcb-icccm1-dev libxcb-sync0 libxcb-sync0-dev libxcb-render-util0 libxcb-render-util0-dev libxcb-xfixes0-dev libxrender-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-glx0-dev libxcb-xinerama0-dev
> 
> On Ubuntu 11.10 icccm1 is replaced by icccm4 and xcv-render-util is not available:
> libxcb1 libxcb1-dev libx11-xcb1 libx11-xcb-dev libxcb-keysyms1 libxcb-keysyms1-dev libxcb-image0 libxcb-image0-dev libxcb-shm0 libxcb-shm0-dev libxcb-icccm4 libxcb-icccm4-dev libxcb-sync0 libxcb-sync0-dev libxcb-xfixes0-dev libxrender-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-glx0-dev libxcb-xinerama0-dev
> The packages for xcv-render-util can be installed manually from http://packages.ubuntu.com/natty/libxcb-render-util0 and http://packages.ubuntu.com/natty/libxcb-render-util0-dev
> 
> On Ubuntu 12.04 icccm1 is replaced by icccm4 and xcv-render-util can be installed automatically:
> libxcb1 libxcb1-dev libx11-xcb1 libx11-xcb-dev libxcb-keysyms1 libxcb-keysyms1-dev libxcb-image0 libxcb-image0-dev libxcb-shm0 libxcb-shm0-dev libxcb-icccm4 libxcb-icccm4-dev libxcb-sync0 libxcb-sync0-dev libxcb-xfixes0-dev libxrender-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0 libxcb-render-util0-dev libxcb-glx0-dev libxcb-xinerama0-dev

Now I don't have this error, now I'm waiting to see if it's compiling successfully or not ^^

**Comment by piranna** [comment]
i set it to use bundle copy of xcb lib.

**Comment by jaumard** [comment]
After this I do `sudo apt-get install ruby bison flex perf` because of this : 

```
Encountered 5 configuration warning(s):

 ! QtQuick module not found, QML APIs will not be built
 ! Qt not configured to use system libjpeg, QImageDecoder will decode JPEG images
 ! Qt not configured to use system libpng, QImageDecoder will decode PNG images
 ! Missing GStreamer or QtMultimedia, disabling HTML5 media element support
 ! QtWebKitQml will not be build. It is not supported with static linking

The WebKit build was disabled for the following reasons: 
    * Missing gperf from PATH
    * Missing bison from PATH
    * Missing ruby from PATH
    * Missing flex from PATH 
```

Now I have this error : 

```
virtual memory exhausted: Cannot allocate memory
make[2]: *** [.obj/html/HTMLElementsAllInOne.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/parallels/workspace/noGUI/build/qtwebkit/Source/WebCore'
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory `/home/parallels/workspace/noGUI/build/qtwebkit/Source/WebCore'
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2
```

**Comment by Coretool** [comment]
If you just want to work on noGui, you don't have to build this ! Install the Qt 5.5 for your platform and start working on noGui itself! You do not need static version to hack on noGui...

**Comment by jaumard** [comment]
Sorry @Coretool I a noob on this kind of project (I'm a web and mobile dev)... I installed Qt 5.5 and manage to launch noGUI. 

Here is what I want to do : create a desktop application who is able to list/launch apps, manage files/folders, like this nodeOS can boot on it and have a nice UI. Do to this I need a Javascript API to be able to do some actions from embedded Javascript to the nodeOS system. I can try create a bridge between nodeOS -> QT -> embedded JS to do some actions like create folder/files, run commands.

As I understand this project will allow to launch a file or URL on nodeOS under a QT application with a WebView in it.

First : am I in the right place ? ^^ 
Second : are you interested in such functionalities ?

**Comment by piranna** [comment]
What you want to achieve is a plain old webapp. Just develop it for any web
browser and it will work on NodeOS and noGUI.

**Comment by Coretool** [comment]
You don' t need to say sorry ^^ I am not a master of such projects either ! 

What you want to do can all be warpped up into a plain webapp ! See the machine as the server and noGui as the client. All changes on the server will actually happen on your nodeOs machine ! 

It's really cool, that we got somebody who want's to write an actual Desktop / App for a nodeOs with a gui, this motivates me to take the time to work on noGui !

**Comment by jaumard** [comment]
I just read some other issues and what I have in mind is to have access to node API directly from webview but I read that is not what you want to do so it's ok ^^. 
I also read there some interesting desktop projects that can be used for nodeOS so I will more look into this before starting something ^^  
Thanks for your help and explanations :)

**Comment by mitsukaki** [comment]
> Here is what I want to do : create a desktop application who is able to list/launch apps, manage files/folders, like this nodeOS can boot on it and have a nice UI. Do to this I need a Javascript API to be able to do some actions from embedded Javascript to the nodeOS system. I can try create a bridge between nodeOS -> QT -> embedded JS to do some actions like create folder/files, run commands.
> 
> As I understand this project will allow to launch a file or URL on nodeOS under a QT application with a WebView in it.
> 
> First : am I in the right place ? ^^ 
> Second : are you interested in such functionalities ?

Sounds like you'd like to make a desktop manager. You wouldn't need to come this far back. To speed up development, you may want to take a look at the Yunitto module on npm.

**Comment by mitsukaki** [comment]
> I just read some other issues and what I have in mind is to have access to node API directly from webview but I read that is not what you want to do so it's ok ^^. 
> I also read there some interesting desktop projects that can be used for nodeOS so I will more look into this before starting something ^^

Ah I see. Yes it's encouraged to do as much processing as possible on the remote side instead of the host server. Good luck with your project!
