### ISSUE TITLE
new and easier idea

### ISSUE THREAD

**Issue by Coretool** [Coretool/noGUI#12]
I guess you all know phantomjs. It's used to test web pages completly headless and without X. 

Last night I tried something : Open a webpage, screenshoting it and printing the scrennshots to the FB. It works quite well. I still have to add find the optimal way of writing it to the fb and so on but it semms to work. It could replace the other aproach ... 

What do you think about it ? 

/ cc @piranna @lite20

**Comment by piranna** [comment]
Not a bad idea, good to know you got it working :-) How do you manage
keystrokes and the mouse?

**Comment by Coretool** [comment]
I used a toy mouse driver and ignored the keyboard ...

**Comment by piranna** [comment]
> I used a toy mouse driver and ignored the keyboard ...

:-/ Do you know if the binary is fully static?

**Comment by Coretool** [comment]
I wrote it and as far as I know it should be possibel to complie it statically

**Comment by piranna** [comment]
I'm talking about the PhantomJS binary.

**Comment by Coretool** [comment]
Yeah... that makes more sense. Honestly, I didn't check, but since they use qtWebkit, I guess it's possible ...

**Comment by Coretool** [comment]
Yeah, [it's possible](https://github.com/macbre/phantomjs/releases/tag/2.0.0).

**Comment by piranna** [comment]
Well, it's not fully static since it use the dynamic version of libc, but
it's good enough ;-) We could investigate this path since it uses
QtWebengine instead of the deprecated QtWebkit, but I would use it more as
a testbed to know how to compile it ourselves adding the direct support for
framebuffer.

**Comment by Coretool** [comment]
Yeah, that's what I was thinking too because it uses way too much of the computers power (my laptop did heat up about 10°) to be used as everyday GUI.

**Comment by mitsukaki** [comment]
This sounds like an awesome idea. Taking a look at the source we could probably find a nicer way to glue phantom to the framebuffer and get it going.

**Comment by mitsukaki** [comment]
@Coretool could I have the source for your setup? Ty (emailed you about it)
