### ISSUE TITLE
Download tarballs instead of use git

### ISSUE THREAD

**Issue by piranna** [Coretool/noGUI#14]
Use direct download of tarballs instead of download latests source code using `git`. For QtBase the url is http://download.qt.io/official_releases/qt/5.7/5.7.0/submodules/qtbase-opensource-src-5.7.0.tar.gz, maybe we should do first some trials with previous versions due to #13.

**Comment by mitsukaki** [comment]
Are you referring to our build scripts? To download tarballs instead of using git?

**Comment by piranna** [comment]
> Are you referring to our build scripts? To download tarballs instead of
> using git?

Yes, this would remove one dependency (git), make download faster (only
latests files without the changes history) and more important use fixed and
tested versions instead of latest master branch, so environment is easily
replicable and testeable.

**Comment by Coretool** [comment]
We can close this, tars are in use now !

**Comment by piranna** [comment]
:-D
