### ISSUE TITLE
Auto add the `http://`?

### ISSUE THREAD

**Issue by legodude17** [Coretool/noGUI#15]
Why wouldn't it just auto add the `http://` if it didn't exist?

**Comment by piranna** [comment]
It's an option, although this project don't have too much attention lately, we are focused on launching NodeOS 1.0.0 first. You can take a look at it and send pull-requests if you want :-)

**Comment by legodude17** [comment]
Ok. I will send a PR. 😄

**Comment by legodude17** [comment]
Ok I sent the PR and it was accepted.
