### ISSUE TITLE
Optimize git clone

### ISSUE THREAD

**Issue by piranna** [Coretool/noGUI#3]
Configure options from `init-repository` to only download the necesary submodules.

**Comment by Coretool** [comment]
Didn't know that this is a thing ^^ Ok, let's do it !

**Comment by piranna** [comment]
We need to look for the alternative tarballs instead of git clone.

**Comment by Coretool** [comment]
Why ?

**Comment by piranna** [comment]
Using tarballs download will be faster, and also we remove git as
dependency.

**Comment by Coretool** [comment]
Yeah... forgot that NodeOS doesn't have git (full) git support....
