### ISSUE TITLE
Switching to GTK(+)/GTKfb

### ISSUE THREAD

**Issue by Coretool** [Coretool/noGUI#4]
Since QT doesn't allow us to build the webview component (or WebKit) statically, I am thinking about switching to GTK+ since this is much easier to handle (no qmake like things) and allows static versions of WebKit. What do you think about that @piranna ?

**Comment by piranna** [comment]
Downloading Qt it builds by default `qmake`, but the point of not needing it is a plus. We could test it on a different branch...

By the way, PhantomJS has statically compiled Linux builds of headless Chrome, maybe we could use it for inspiration...

**Comment by Coretool** [comment]
Well the problem about headless things is that they are headless... So we have to figure out how to give it a head (in this case egl or linuxfb)

**Comment by piranna** [comment]
> Well the problem about headless things is that they are headless... So we have to figure out how to give it a head (in this case egl or linuxfb)

I think it would be just a matter of not disabling the graphic backends.

**Comment by Coretool** [comment]
So we are going to build the phantomjs thingy and just add the egl / linuxfb flag (?)... Sounds like a plan

**Comment by piranna** [comment]
Sort of... my idea is to use PhantomJS as basis but only use the flags we see could fit to out purposses.

**Comment by Coretool** [comment]
Yeah, sure... we will probably need more than they need...
